import { Routes, Route, Link, NavLink, useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Code2, Menu, X, CheckCircle2, Search, Mail, UserRound, LogOut } from 'lucide-react';
import { useEffect, useState } from 'react';
import { productsApi, contentApi, contactApi, testimonialsApi, newsletterApi, authApi, getStoredAuthUser, saveAuthUser, clearAuthUser, siteSettingsApi } from './services/api.js';
import Admin from './admin/Admin.jsx';
import Login from './auth/Login.jsx';
import Register from './auth/Register.jsx';
import CustomerDashboard from './customer/CustomerDashboard.jsx';
import CustomerSettings from './customer/CustomerSettings.jsx';

const fallback = {
  name:'primeStack', tagline:'Software that moves your business forward.', description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.', email:'hello@primestack.dev', phone:'', logoUrl:'', faviconUrl:'', founderImageUrl:'', primaryColor:'#111827', accentColor:'#2563eb', backgroundColor:'#ffffff', textColor:'#111827',
  nav:[{label:'Home',path:'/',visible:true},{label:'Products',path:'/products',visible:true},{label:'Services',path:'/services',visible:true},{label:'Case Studies',path:'/case-studies',visible:true},{label:'Technology',path:'/technology',visible:true},{label:'Blog',path:'/blog',visible:true},{label:'Careers',path:'/careers',visible:true},{label:'About',path:'/about',visible:true}],
  sections:{hero:true,stats:true,products:true,services:true,caseStudies:true,testimonials:true,blog:true,cta:true,newsletter:true},
  home:{eyebrow:'SOFTWARE PRODUCT COMPANY',title:'Software that moves your business forward.',description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.',primaryCtaLabel:'Explore products',secondaryCtaLabel:'Work with us',productsEyebrow:'OUR PRODUCTS',productsTitle:'Software built to matter.',ctaEyebrow:'BUILD WITH US',ctaTitle:'Have a software idea?',ctaText:"Let's turn your complex business challenge into a product people love to use."},
  pages:{services:{eyebrow:'CAPABILITIES',title:'Services',text:'From product strategy to scalable infrastructure, we build around the way your business actually works.'},about:{eyebrow:'THE COMPANY',title:'We build what comes next.',text:'primeStack turns complex business problems into elegant, dependable digital products.'},technology:{eyebrow:'ENGINEERING',title:'Technology expertise',text:'Modern tools selected for reliability, performance, security and maintainability.'},contact:{eyebrow:"LET'S TALK",title:'Build something valuable.',text:'Tell us what you are building, what problem you need to solve and where you want to go next.'},products:{eyebrow:'PRODUCT PORTFOLIO',title:'Products',text:'Purpose-built solutions designed to simplify work, unlock insight and accelerate growth.'},caseStudies:{eyebrow:'PROVEN OUTCOMES',title:'Case studies',text:'Real projects, real challenges, measurable results.'},blog:{eyebrow:'INSIGHTS',title:'Blog',text:'Ideas, lessons and practical insights from our team.'},careers:{eyebrow:'JOIN THE TEAM',title:'Careers',text:'Build meaningful products with a team that cares about quality.'}},
  services:[{name:'Custom Software Development',description:'Business software designed around your workflows.'},{name:'Project Delivery',description:'Planning, coordination and execution from idea to completion.'}], technologies:['React','Node.js','MongoDB','Cloud'], values:['Quality','Transparency','Safety','Customer Focus'], stats:[{value:'10+',label:'Products'},{value:'50K+',label:'Users served'},{value:'99.9%',label:'Uptime'},{value:'8+',label:'Years experience'}], footer:{description:'We build dependable solutions that create measurable business value.',copyright:'All rights reserved.'}
};

const mergeSite = (s={}) => {
  const configuredNav=Array.isArray(s.nav)&&s.nav.length?s.nav:fallback.nav;
  const withoutHome=configuredNav.filter(x=>x.path!=='/');
  const nav=[{label:'Home',path:'/',visible:true},...withoutHome];
  return {...fallback,...s,nav,sections:{...fallback.sections,...(s.sections||{})},home:{...fallback.home,...(s.home||{})},pages:{...fallback.pages,...(s.pages||{})},footer:{...fallback.footer,...(s.footer||{})}};
};

function PublicLayout({children,site}) {
  const [open,setOpen]=useState(false), [user,setUser]=useState(()=>getStoredAuthUser()), navigate=useNavigate();
  const nav=(site.nav||fallback.nav).filter(x=>x.visible!==false);
  useEffect(()=>{authApi.me().then(r=>{const u=r.data?.data?.user;if(u){saveAuthUser(u);setUser(u)}}).catch(()=>{});const sync=()=>setUser(getStoredAuthUser());window.addEventListener('primeStackAuthChanged',sync);return()=>window.removeEventListener('primeStackAuthChanged',sync)},[]);
  const signOut=async()=>{await authApi.logout().catch(()=>{});clearAuthUser();setUser(null);navigate('/login',{replace:true})};
  return <><header><Link className="brand" to="/"><span className="logo">{site.logoUrl?<img src={site.logoUrl} alt=""/>:<Code2 size={19}/>}</span>{site.name}</Link><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(x=><NavLink key={x.path} to={x.path} onClick={()=>setOpen(false)}>{x.label}</NavLink>)}{user?<><Link className="navLogin" to={user.role==='Admin'||user.role==='Editor'?'/admin':'/dashboard'}><UserRound size={15}/>{user.role==='Admin'||user.role==='Editor'?'Admin':'Dashboard'}</Link><button className="navLogin navLogout" onClick={signOut}><LogOut size={15}/>Sign out</button></>:<Link className="navLogin" to="/login">Sign in</Link>}<Link className="navCta" to="/contact">{site.home?.secondaryCtaLabel||'Work With Us'}</Link></nav></header><main>{children}</main><footer><div><div className="brand"><span className="logo"><Code2 size={19}/></span>{site.name}</div><p>{site.footer?.description||site.description}</p><a href={`mailto:${site.email}`}>{site.email}</a>{site.phone&&<p>{site.phone}</p>}</div><div><b>Explore</b><Link to="/">Home</Link><Link to="/products">Products</Link><Link to="/services">Services</Link><Link to="/case-studies">Case Studies</Link><Link to="/blog">Blog</Link></div><div><b>Company</b><Link to="/about">About</Link><Link to="/careers">Careers</Link><Link to="/contact">Contact</Link></div><div><b>Account</b>{user?<><Link to={user.role==='Admin'||user.role==='Editor'?'/admin':'/dashboard'}>{user.role==='Admin'||user.role==='Editor'?'Admin dashboard':'Customer dashboard'}</Link><button className="footerLogout" onClick={signOut}>Sign out</button></>:<><Link to="/login">Customer sign in</Link><Link to="/register">Create account</Link></>}<Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></footer></>;
}

function Home({site}) {
  const [products,setProducts]=useState([]),[testimonials,setTestimonials]=useState([]); const sections=site.sections||fallback.sections,h=site.home||fallback.home;
  useEffect(()=>{if(sections.products){productsApi.list({featured:true,limit:4}).then(r=>{const data=r.data?.data||[];if(data.length){setProducts(data);return}return productsApi.list({limit:4}).then(fallbackResponse=>setProducts(fallbackResponse.data?.data||[]))}).catch(()=>setProducts([]));}if(sections.testimonials)testimonialsApi.list({featured:true}).then(r=>setTestimonials((r.data?.data||[]).slice(0,3))).catch(()=>setTestimonials([]))},[sections.products,sections.testimonials]);
  const founderImageUrl=site.founderImageUrl||site.heroImageUrl||site.imageUrl||site.home?.heroImageUrl||site.home?.imageUrl||'';
  const founderStyle=founderImageUrl?{'--founder-image':`url(${JSON.stringify(founderImageUrl)})`}:{};
  return <>{sections.hero&&<section className="hero"><div><span className="eyebrow">{h.eyebrow}</span><h1>{h.title||site.tagline}</h1><p>{h.description||site.description}</p><div className="actions"><Link className="btn primary" to="/products">{h.primaryCtaLabel} <ArrowRight size={18}/></Link><Link className="btn secondary" to="/contact">{h.secondaryCtaLabel}</Link></div><div className="heroTrust"><span>Quality focused</span><span>Built to scale</span><span>Human support</span></div></div><motion.div className="mockup" style={founderStyle} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}>{founderImageUrl&&<img className="heroFounderImage" src={founderImageUrl} alt="primeStack" onError={e=>{e.currentTarget.style.display='none'}}/>}<div className="mockupOverlay"/><div className="mockHeader"><span/><span/><span/></div><div className="mockTitle"/><div className="mockgrid"><div/><div/><div/><div/></div></motion.div></section>}{sections.stats&&<section className="trust">{(site.stats||[]).map((s,i)=><div key={i}><strong>{s.value}</strong><span>{s.label}</span></div>)}</section>}{sections.products&&<section><div className="sectionHead"><div><span className="eyebrow">{h.productsEyebrow}</span><h2>{h.productsTitle}</h2></div><Link to="/products">View all <ArrowRight size={16}/></Link></div><ProductGrid products={products}/></section>}{sections.testimonials&&testimonials.length>0&&<section><span className="eyebrow">CUSTOMER VOICE</span><h2>Trusted by teams that value results.</h2><div className="grid">{testimonials.map(t=><div className="card" key={t._id}><p className="quote">“{t.quote}”</p><h3>{t.customerName}</h3><p>{[t.position,t.company].filter(Boolean).join(' · ')}</p></div>)}</div></section>}{sections.cta&&<section className="cta"><span className="eyebrow">{h.ctaEyebrow}</span><h2>{h.ctaTitle}</h2><p>{h.ctaText}</p><Link className="btn primary" to="/contact">{h.primaryCtaLabel} <ArrowRight size={18}/></Link></section>}{sections.newsletter&&<section><Newsletter/></section>}</>;
}
function ProductGrid({products}){if(!products?.length)return <div className="empty">No published items yet. Add products from the admin workspace.</div>;return <div className="grid">{products.map(p=><Link className="card" to={`/products/${p.slug}`} key={p._id}><div className="productLogo">{p.logo?<img src={p.logo} alt=""/>:<Code2/>}</div><span className="pill">{p.category||'Business'} · {p.status}</span><h3>{p.name}</h3><p>{p.tagline||p.description}</p><span className="learn">Explore <ArrowRight size={15}/></span></Link>)}</div>}
function Page({page,site,children,eyebrow,title,text}){const p=site.pages?.[page]||{};return <><section className="pageHead"><span className="eyebrow">{p.eyebrow||eyebrow}</span><h1>{p.title||title}</h1><p>{p.text||text}</p></section><section>{children}</section></>}
function Products({site}){const[products,setProducts]=useState([]),[search,setSearch]=useState('');useEffect(()=>{const t=setTimeout(()=>productsApi.list({search,limit:24}).then(r=>setProducts(r.data?.data||[])).catch(()=>setProducts([])),200);return()=>clearTimeout(t)},[search]);return <Page page="products" site={site} eyebrow="PRODUCT PORTFOLIO" title="Products" text="Purpose-built solutions designed to simplify work, unlock insight and accelerate growth."><div className="search"><Search/><input placeholder="Search products..." value={search} onChange={e=>setSearch(e.target.value)}/></div><ProductGrid products={products}/></Page>}
function ProductDetails(){const{slug}=useParams(),[p,setP]=useState(null);useEffect(()=>{productsApi.get(slug).then(r=>setP(r.data?.data)).catch(()=>setP(false))},[slug]);if(p===false)return <NotFound/>;if(!p)return <Loading/>;return <><section className="detailHero"><span className="eyebrow">{p.category||'PRODUCT'} · {p.status}</span><h1>{p.name}</h1><h2>{p.tagline}</h2><p>{p.description}</p><div className="actions"><a className="btn primary" href={p.websiteUrl||'/contact'} target={p.websiteUrl?'_blank':undefined} rel="noreferrer">{p.websiteUrl?'Open':'Talk to us'} <ArrowRight size={18}/></a><Link className="btn secondary" to="/contact">Contact</Link></div></section><section><div className="detailGrid"><div><h2>Built for real business impact.</h2><p>{p.longDescription||p.description}</p></div><div>{(p.features||[]).map((f,i)=><div className="feature" key={i}><CheckCircle2/><div><h3>{f.title}</h3><p>{f.description}</p></div></div>)}</div></div></section></>}
function Services({site}){return <Page page="services" site={site} eyebrow="CAPABILITIES" title="Services" text="Solutions designed around the way your business actually works."><div className="serviceGrid">{(site.services||[]).map((x,i)=><div className="service" key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{x.name||x.title}</h3><p>{x.description}</p></div>)}{!site.services?.length&&<div className="empty">Add services from Website Builder.</div>}</div></Page>}
function DynamicList({type,page,title,eyebrow,text,prefix,site}){const[items,setItems]=useState([]);useEffect(()=>{contentApi.list(type).then(r=>setItems(r.data?.data||[])).catch(()=>setItems([]))},[type]);return <Page page={page} site={site} eyebrow={eyebrow} title={title} text={text}><div className="grid">{items.map(x=><Link className="card" to={`${prefix}/${x.slug}`} key={x._id}><span className="pill">{x.category||x.industry||x.department||'Featured'}</span><h3>{x.title}</h3><p>{x.description||x.challenge||x.content}</p><span className="learn">Read more <ArrowRight size={15}/></span></Link>)}</div>{!items.length&&<div className="empty">Content will appear here once published from the admin workspace.</div>}</Page>}
function DynamicDetail({type}){const{slug}=useParams(),[item,setItem]=useState(null);useEffect(()=>{contentApi.get(type,slug).then(r=>setItem(r.data?.data)).catch(()=>setItem(false))},[type,slug]);if(item===false)return <NotFound/>;if(!item)return <Loading/>;return <article className="article"><span className="eyebrow">{item.category||item.industry||item.department||type.toUpperCase()}</span><h1>{item.title}</h1>{item.coverImage&&<img className="articleImage" src={item.coverImage} alt=""/>}<p className="lead">{item.description||item.challenge}</p>{item.challenge&&<><h2>Challenge</h2><p className="articleBody">{item.challenge}</p></>}{item.solution&&<><h2>Solution</h2><p className="articleBody">{item.solution}</p></>}<div className="articleBody">{item.content}</div>{item.results?.length>0&&<><h2>Results</h2><ul>{item.results.map((x,i)=><li key={i}>{x}</li>)}</ul>}</article>}
function About({site}){return <Page page="about" site={site} eyebrow="THE COMPANY" title="We build what comes next."><div className="aboutGrid"><div><h2>Mission</h2><p>{site.description}</p></div><div><h2>Values</h2><div className="values">{(site.values||[]).map(x=><span key={x}>{x}</span>)}</div></div></div></Page>}
function Technology({site}){return <Page page="technology" site={site} eyebrow="ENGINEERING" title="Technology expertise"><div className="techGrid">{(site.technologies||[]).map(x=><div key={x}>{x}</div>)}</div></Page>}
function Contact({site}){const[form,setForm]=useState({}),[state,setState]=useState('');const submit=async e=>{e.preventDefault();setState('loading');try{await contactApi.create(form);setState('done');setForm({})}catch{setState('error')}};return <Page page="contact" site={site} eyebrow="LET'S TALK" title="Build something valuable." text="Tell us what you are building and where you want to go next."><form className="form" onSubmit={submit}>{['name','email','company','phone','budget'].map(x=><input key={x} required={['name','email'].includes(x)} type={x==='email'?'email':'text'} placeholder={x[0].toUpperCase()+x.slice(1)} value={form[x]||''} onChange={e=>setForm({...form,[x]:e.target.value})}/>)}<select value={form.projectType||''} onChange={e=>setForm({...form,projectType:e.target.value})}><option value="">Project type</option>{['General enquiry','Project','Partnership','Support','Sales','Other'].map(x=><option key={x}>{x}</option>)}</select><textarea required placeholder="Tell us about your project..." rows="7" value={form.message||''} onChange={e=>setForm({...form,message:e.target.value})}/><button className="btn primary" disabled={state==='loading'}>{state==='loading'?'Sending…':'Send inquiry'} <ArrowRight size={18}/></button>{state==='done'&&<p className="success">Thanks — your inquiry has been received.</p>}{state==='error'&&<p className="error">Unable to send. Please try again.</p>}</form></Page>}
function Newsletter(){const[email,setEmail]=useState(''),[state,setState]=useState('');return <div className="newsletter"><div><span className="eyebrow">UPDATES</span><h3>Stay informed.</h3><p>Useful ideas. No noise.</p></div><form onSubmit={async e=>{e.preventDefault();setState('loading');try{await newsletterApi.subscribe(email);setState('done');setEmail('')}catch{setState('error')}}}><Mail size={18}/><input type="email" required placeholder="you@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn primary">{state==='done'?'Subscribed':'Subscribe'}</button></form></div>}
function Loading(){return <div className="loading">Loading…</div>}
function NotFound(){return <section className="pageHead"><span className="eyebrow">404</span><h1>Page not found</h1><p>The page you are looking for does not exist.</p><Link className="btn primary" to="/">Back home</Link></section>}
function PublicRoutes({site}){return <PublicLayout site={site}><Routes><Route path="/" element={<Home site={site}/>}/><Route path="/products" element={<Products site={site}/>}/><Route path="/products/:slug" element={<ProductDetails/>}/><Route path="/services" element={<Services site={site}/>}/><Route path="/about" element={<About site={site}/>}/><Route path="/technology" element={<Technology site={site}/>}/><Route path="/case-studies" element={<DynamicList type="case-studies" page="caseStudies" title="Case studies" eyebrow="PROVEN OUTCOMES" text="Real projects, real challenges, measurable results." prefix="/case-studies" site={site}/>}/><Route path="/case-studies/:slug" element={<DynamicDetail type="case-studies"/>}/><Route path="/blog" element={<DynamicList type="blog" page="blog" title="Blog" eyebrow="INSIGHTS" text="Ideas and practical insights." prefix="/blog" site={site}/>}/><Route path="/blog/:slug" element={<DynamicDetail type="blog"/>}/><Route path="/careers" element={<DynamicList type="jobs" page="careers" title="Careers" eyebrow="JOIN THE TEAM" text="Build meaningful work with a team that cares." prefix="/careers" site={site}/>}/><Route path="/careers/:slug" element={<DynamicDetail type="jobs"/>}/><Route path="/contact" element={<Contact site={site}/>}/><Route path="/privacy" element={<Page site={site} eyebrow="LEGAL" title="Privacy" text="How we handle information and protect your privacy."><div className="articleBody"><p>We only use information necessary to provide and improve our services, respond to inquiries and operate the website.</p></div></Page>}/><Route path="/terms" element={<Page site={site} eyebrow="LEGAL" title="Terms" text="The terms that govern use of this website."><div className="articleBody"><p>Use of this website is subject to applicable laws and responsible use of our content and services.</p></div></Page>}/><Route path="*" element={<NotFound/>}/></Routes></PublicLayout>}

export default function App(){const[site,setSite]=useState(fallback);useEffect(()=>{siteSettingsApi.get().then(r=>{if(r.data?.data)setSite(mergeSite(r.data.data))}).catch(()=>{})},[]);const founderImageUrl=site.founderImageUrl||site.heroImageUrl||site.imageUrl||site.home?.heroImageUrl||site.home?.imageUrl||'';const founderCss=founderImageUrl?'url('+JSON.stringify(founderImageUrl)+')':'none';return <><style>{`:root{--brand-primary:${site.primaryColor};--brand-accent:${site.accentColor};--brand-bg:${site.backgroundColor};--brand-text:${site.textColor};--founder-image:${founderCss}}`}</style><Routes><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/dashboard" element={<CustomerDashboard/>}/><Route path="/dashboard/settings" element={<CustomerSettings/>}/><Route path="/admin/login" element={<Login/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<PublicRoutes site={site}/>}/></Routes></>}
