import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowRight,Box,ClipboardList,LogOut,Mail,Settings,ShieldCheck} from 'lucide-react';
import {api} from '../services/api.js';

export default function CustomerDashboard(){
 const [dashboard,setDashboard]=useState(null);const [error,setError]=useState('');const nav=useNavigate();
 const load=async()=>{try{const r=await api.get('/customer/dashboard');setDashboard(r.data.data)}catch(e){if(e.response?.status===401)nav('/login');else setError(e.response?.data?.message||'Unable to load dashboard.')}};
 useEffect(()=>{load()},[]);
 const logout=async()=>{await api.post('/auth/logout').catch(()=>{});nav('/login')};
 if(!dashboard&&!error)return <div className="dashboardLoading">Loading your workspace...</div>;
 if(error)return <div className="dashboardLoading"><p className="error">{error}</p><button className="btn primary" onClick={load}>Retry</button></div>;
 const {user,stats,requests}=dashboard;
 return <div className="customerShell"><aside className="dashboardSide"><Link className="dashboardBrand" to="/"><span className="logo">&lt;/&gt;</span><span>primeStack</span></Link><nav><Link className="active" to="/dashboard"><Box/>Overview</Link><Link to="/products"><ClipboardList/>Products</Link><Link to="/dashboard/settings"><Settings/>Account</Link></nav><button className="sideLogout" onClick={logout}><LogOut/>Sign out</button></aside><main className="customerMain"><header className="dashboardHeader"><div><span className="eyebrow">CUSTOMER WORKSPACE</span><h1>Good to see you, {user.name.split(' ')[0]}.</h1><p>Here is an overview of your primeStack account.</p></div><div className="profileChip"><span>{user.name.charAt(0).toUpperCase()}</span><div><b>{user.name}</b><small>{user.email}</small></div></div></header><section className="customerStats"><div><span>Account</span><strong>Active</strong><small><ShieldCheck size={14}/> Protected</small></div><div><span>Products</span><strong>{stats.products}</strong><small>Available to you</small></div><div><span>Requests</span><strong>{stats.requests}</strong><small>Contact enquiries</small></div></section><section className="dashboardSection"><div className="dashboardSectionHead"><div><span className="eyebrow">YOUR PRODUCTS</span><h2>Explore our products</h2></div><Link to="/products">View catalog <ArrowRight size={16}/></Link></div><div className="dashboardProductGrid">{dashboard.products.map(p=><Link className="dashboardProduct" key={p._id} to={`/products/${p.slug}`}><span className="pill">{p.category} · {p.status}</span><h3>{p.name}</h3><p>{p.tagline||p.description}</p><span>View product <ArrowRight size={15}/></span></Link>)}</div></section><section className="dashboardSection"><div className="dashboardSectionHead"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Your enquiries</h2></div><Link to="/contact">New enquiry <ArrowRight size={16}/></Link></div>{requests.length?<div className="requestList">{requests.map(x=><div className="requestItem" key={x._id}><div><b>{x.projectType||'General enquiry'}</b><p>{x.message}</p></div><span className={`status status-${x.status.toLowerCase().replace(/\s/g,'-')}`}>{x.status}</span></div>)}</div>:<div className="dashboardEmpty"><Mail/><h3>No enquiries yet</h3><p>Tell us what you're building and our team will get back to you.</p><Link className="btn primary" to="/contact">Start a conversation</Link></div>}</section></main></div>