import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import {api} from '../services/api.js';

export default function Register(){
 const [form,setForm]=useState({name:'',email:'',password:'',confirmPassword:''});
 const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const nav=useNavigate();
 const submit=async e=>{e.preventDefault();setError('');if(form.password.length<8)return setError('Password must be at least 8 characters.');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');setLoading(true);try{await api.post('/auth/register',{name:form.name,email:form.email,password:form.password});nav('/dashboard')}catch(err){setError(err.response?.data?.message||'Unable to create your account.')}finally{setLoading(false)}};
 return <div className="authPage"><div className="authPanel"><div className="authBrand"><span className="logo">&lt;/&gt;</span><span>primeStack</span></div><span className="eyebrow">CUSTOMER ACCOUNT</span><h1>Create your account.</h1><p className="authLead">Get access to your products, requests and account workspace.</p><form className="form authForm" onSubmit={submit}><label>Full name<input required autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/></label><label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@company.com"/></label><label>Password<input required type="password" minLength="8" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/></label><label>Confirm password<input required type="password" minLength="8" autoComplete="new-password" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} placeholder="Repeat your password"/></label><button className="btn primary" disabled={loading}>{loading?'Creating account...':'Create account'} <ArrowRight size={18}/></button>{error&&<p className="error">{error}</p>}</form><p className="authSwitch">Already have an account? <Link to="/login">Sign in</Link></p></div><aside className="authAside"><span className="eyebrow">PRIMESTACK CUSTOMER PORTAL</span><h2>Your software workspace, in one place.</h2><p>Manage your relationship with primeStack from a secure customer dashboard.</p><ul><li><CheckCircle2/>View your products and services</li><li><CheckCircle2/>Track enquiries and requests</li><li><CheckCircle2/>Manage your profile and security</li></ul></aside></div>
}
