import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {ArrowRight,CheckCircle2,Code2} from 'lucide-react';
import api,{siteSettingsApi} from '../services/api.js';

const fallbackNav=[['Products','/products'],['Services','/services'],['Case Studies','/case-studies'],['Technology','/technology'],['Blog','/blog'],['Careers','/careers'],['About','/about']];
export default function Register(){
 const [form,setForm]=useState({name:'',email:'',password:'',confirmPassword:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [site,setSite]=useState({name:'primeStack',nav:[],home:{secondaryCtaLabel:'Work With Us'}}); const navg=useNavigate();
 useEffect(()=>{siteSettingsApi.get().then(r=>{const s=r.data?.data||{};setSite({name:s.name||'primeStack',nav:Array.isArray(s.nav)?s.nav:[],home:s.home||{}})}).catch(()=>{})},[]);
 const publicNav=(site.nav?.length?site.nav:fallbackNav.map(([label,path])=>({label,path,visible:true}))).filter(x=>x.visible!==false&&x.path);
 const submit=async e=>{e.preventDefault();setError('');if(form.password.length<8)return setError('Password must be at least 8 characters.');if(form.password!==form.confirmPassword)return setError('Passwords do not match.');setLoading(true);try{await api.post('/auth/register',{name:form.name,email:form.email,password:form.password});navg('/dashboard')}catch(err){setError(err.response?.data?.message||'Unable to create your account.')}finally{setLoading(false)}};
 return <div className="authShell"><header className="authNavbar"><Link className="brand" to="/"><span className="logo"><Code2 size={19}/></span>{site.name}</Link><nav>{publicNav.map(x=><Link key={`${x.path}-${x.label}`} to={x.path}>{x.label}</Link>)}<Link className="navLogin" to="/login">Sign in</Link><Link className="navCta" to="/contact">{site.home?.secondaryCtaLabel||'Work With Us'}</Link></nav><Link className="authMobileHome" to="/">Home</Link></header><div className="authPage"><div className="authPanel"><div className="authBrand"><span className="logo">&lt;/&gt;</span><span>{site.name}</span></div><span className="eyebrow">CUSTOMER ACCOUNT</span><h1>Create your account.</h1><p className="authLead">Get access to your products, requests and account workspace.</p><form className="form authForm" onSubmit={submit}><label>Full name<input required autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/></label><label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@company.com"/></label><label>Password<input required type="password" minLength="8" autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/></label><label>Confirm password<input required type="password" minLength="8" autoComplete="new-password" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} placeholder="Repeat your password"/></label><button className="btn primary" disabled={loading}>{loading?'Creating account...':'Create account'} <ArrowRight size={18}/></button>{error&&<p className="error">{error}</p>}</form><p className="authSwitch">Already have an account? <Link to="/login">Sign in</Link></p></div><aside className="authAside"><span className="eyebrow">{site.name.toUpperCase()} CUSTOMER PORTAL</span><h2>Your software workspace, in one place.</h2><p>Manage your relationship with {site.name} from a secure customer dashboard.</p><ul><li><CheckCircle2/>View your products and services</li><li><CheckCircle2/>Track enquiries and requests</li><li><CheckCircle2/>Manage your profile and security</li></ul></aside></div></div>
}
