import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../services/api.js';

const navItems = [
  ['overview', 'Overview'], ['products', 'Products'], ['blog', 'Blog posts'],
  ['case-studies', 'Case studies'], ['jobs', 'Careers'], ['testimonials', 'Testimonials'], ['contacts', 'Inquiries']
];
const blankProduct = { name:'', slug:'', tagline:'', description:'', longDescription:'', category:'Business', status:'Live', featured:true, published:true, websiteUrl:'', documentationUrl:'', features:[{title:'',description:''}], benefits:[] };
const blankContent = { title:'', slug:'', description:'', content:'', category:'', industry:'', department:'', location:'', employmentType:'', experienceLevel:'', challenge:'', solution:'', technologies:'', results:'', requirements:'', responsibilities:'', coverImage:'', author:'', published:true };
const blankTestimonial = { quote:'', customerName:'', position:'', company:'', photo:'', featured:false };
const split = x => String(x || '').split(',').map(s=>s.trim()).filter(Boolean);
const slugify = x => String(x || '').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

export default function Admin(){
  const [user,setUser]=useState(null), [stats,setStats]=useState({}), [data,setData]=useState([]), [contacts,setContacts]=useState([]);
  const [tab,setTab]=useState('overview'), [editing,setEditing]=useState(null), [form,setForm]=useState(blankProduct), [search,setSearch]=useState('');
  const [message,setMessage]=useState(''), [error,setError]=useState(''), [loading,setLoading]=useState(false), [sidebar,setSidebar]=useState(false);
  const navigate=useNavigate();
  const isContent=['blog','case-studies','jobs'].includes(tab), isProduct=tab==='products', isTestimonial=tab==='testimonials';
  const title=useMemo(()=>navItems.find(x=>x[0]===tab)?.[1]||'Overview',[tab]);

  const load=async()=>{
    try{
      setError('');
      const me=await api.get('/auth/me'); const currentUser=me.data.data.user;
      if(!['Admin','Editor'].includes(currentUser.role)){setUser(false);return} setUser(currentUser);
      const s=await api.get('/dashboard/stats'); setStats(s.data.data||{});
      if(tab==='overview') return;
      if(tab==='contacts'){const c=await api.get('/contact');setContacts(c.data.data||[])}
      else if(isProduct){const p=await api.get('/products?limit=100');setData(p.data.data||[])}
      else if(isTestimonial){const t=await api.get('/testimonials');setData(t.data.data||[])}
      else if(isContent){const c=await api.get(`/${tab}`);setData(c.data.data||[])}
    }catch(e){if(e.response?.status===401||e.response?.status===403)setUser(false);else setError(e.response?.data?.message||'Unable to load dashboard')}
  };
  useEffect(()=>{load()},[tab]);
  if(user===false)return <div className="loading"><h2>Admin authentication required</h2><button className="btn primary" onClick={()=>navigate('/login?mode=admin')}>Sign in as Admin</button></div>;
  if(!user)return <div className="loading">Loading PrimeStack CMS...</div>;

  const reset=()=>{setEditing(null);setForm(isProduct?{...blankProduct,features:[{title:'',description:''}]}:isTestimonial?{...blankTestimonial}:{...blankContent});setMessage('');setError('');};
  const edit=x=>{setEditing(x._id);if(isProduct)setForm({...blankProduct,...x,features:x.features?.length?x.features:[{title:'',description:''}]});else if(isTestimonial)setForm({...blankTestimonial,...x});else setForm({...blankContent,...x,technologies:(x.technologies||[]).join(', '),results:(x.results||[]).join(', '),requirements:(x.requirements||[]).join(', '),responsibilities:(x.responsibilities||[]).join(', ')});window.scrollTo({top:0,behavior:'smooth'});};
  const save=async e=>{e.preventDefault();setLoading(true);setMessage('');setError('');try{let body={...form};if(isProduct){body.slug=body.slug||slugify(body.name);body.features=body.features.filter(x=>x.title||x.description)}else if(isContent){body.slug=body.slug||slugify(body.title);body.type=tab;['technologies','results','requirements','responsibilities'].forEach(k=>body[k]=split(body[k]));body.publishedAt=body.publishedAt||new Date().toISOString()}let endpoint=isProduct?'/products':isTestimonial?'/testimonials':`/${tab}`;if(editing)await api.put(`${endpoint}/${editing}`,body);else await api.post(endpoint,body);setMessage(editing?'Changes saved successfully.':'Created successfully.');reset();await load()}catch(e){setError(e.response?.data?.message||'Save failed')}finally{setLoading(false)}};
  const remove=async id=>{if(!window.confirm(`Delete this item permanently?`))return;try{const endpoint=isProduct?'/products':isTestimonial?'/testimonials':`/${tab}`;await api.delete(`${endpoint}/${id}`);setMessage('Deleted successfully.');load()}catch(e){setError(e.response?.data?.message||'Delete failed')}};
  const setField=(k,v)=>setForm(f=>({...f,[k]:v}));
  const filtered=data.filter(x=>String(x.name||x.title||x.customerName||'').toLowerCase().includes(search.toLowerCase()));
  const cards=[['products','Products',stats.products||0,'Manage your product portfolio'],['blog','Blog posts',stats.blog||0,'Publish and manage articles'],['case-studies','Case studies',stats.caseStudies||0,'Showcase client outcomes'],['jobs','Open jobs',stats.jobs||0,'Manage open positions'],['contacts','New inquiries',stats.newContacts||0,'Review incoming leads']];

  const Overview=()=> <>
    <div className="welcomePanel"><div><span className="eyebrow">ADMIN WORKSPACE</span><h1>Good to see you, {user.name?.split(' ')[0]||'Admin'}.</h1><p>Monitor PrimeStack, manage content, and keep your digital experience up to date.</p></div><div className="quickActions"><button className="btn primary" onClick={()=>setTab('products')}>+ New product</button><button className="btn secondary" onClick={()=>setTab('blog')}>Write post</button></div></div>
    <div className="stats">{cards.map(([k,l,n,d])=><button className="statCard" key={k} onClick={()=>setTab(k)}><span className="statIcon">{k==='contacts'?'✦':k==='products'?'▦':k==='blog'?'✎':k==='jobs'?'⌁':'◈'}</span><span className="eyebrow">{l}</span><strong>{n}</strong><small>{d}</small></button>)}</div>
    <div className="overviewGrid"><div className="adminList"><div className="listHeader"><div><span className="eyebrow">CONTENT</span><h2>Workspace shortcuts</h2></div></div><div className="shortcutGrid">{navItems.slice(1).map(([k,l])=><button className="shortcut" key={k} onClick={()=>setTab(k)}><b>{l}</b><span>Open workspace →</span></button>)}</div></div><div className="adminList"><div className="listHeader"><div><span className="eyebrow">SYSTEM</span><h2>Admin status</h2></div></div><div className="statusList"><div><span>Signed in as</span><b>{user.email}</b></div><div><span>Access level</span><b>{user.role}</b></div><div><span>API status</span><b className="statusLive">● Operational</b></div></div></div></div>
  </>;

  return <div className="adminShell">
    <aside className={`adminSidebar ${sidebar?'open':''}`}><div className="sideBrand"><span className="sideLogo">P</span><div><b>primeStack</b><small>CMS</small></div></div><div className="sideLabel">WORKSPACE</div><nav className="sideNav">{navItems.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>{setTab(k);setSidebar(false);reset()}}><span>{k==='overview'?'⌂':k==='products'?'▦':k==='blog'?'✎':k==='case-studies'?'◈':k==='jobs'?'⌁':k==='testimonials'?'♡':'✦'}</span>{l}{k==='contacts'&&stats.newContacts>0?<em>{stats.newContacts}</em>:null}</button>)}</nav><div className="sideBottom"><div className="sideUser"><span>{(user.name||'A').charAt(0).toUpperCase()}</span><div><b>{user.name||'Admin'}</b><small>{user.role}</small></div></div><button className="sideSignout" onClick={async()=>{await api.post('/auth/logout');navigate('/login?mode=admin')}}>Sign out</button></div></aside>
    <main className="adminMain"><header className="adminHeader"><button className="mobileMenu" onClick={()=>setSidebar(!sidebar)}>☰</button><div><span className="eyebrow">PRIMESTACK CMS</span><b>{title}</b></div><div className="headerActions"><Link className="btn secondary" to="/">↗ View site</Link><button className="profileChip" onClick={()=>setTab('overview')}><span>{(user.name||'A').charAt(0).toUpperCase()}</span>{user.name||'Admin'}</button></div></header><div className="adminContent">
      {message&&<div className="notice success">✓ {message}</div>}{error&&<div className="notice error">! {error}</div>}
      {tab==='overview'?<Overview/>:<>
        <div className="pageIntro"><div><span className="eyebrow">CONTENT MANAGEMENT</span><h1>{title}</h1><p>Create, update and publish your {title.toLowerCase()} from one workspace.</p></div><button className="btn primary" onClick={reset}>+ Add {title.slice(0,-1)}</button></div>
        {tab!=='contacts'&&<div className="toolbar"><div className="adminSearch">⌕<input placeholder={`Search ${title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{filtered.length} {filtered.length===1?'item':'items'}</span></div>}
        {tab==='contacts'?<div className="adminList"><div className="listHeader"><div><span className="eyebrow">LEADS</span><h2>Contact inquiries</h2></div></div>{contacts.map(c=><div className="adminRow" key={c._id}><div><b>{c.name} · {c.email}</b><span>{c.company||'No company'} · {c.projectType||'General'} · {new Date(c.createdAt).toLocaleString()}</span><p>{c.message}</p></div><div className="actions"><select value={c.status} onChange={async e=>{await api.put(`/contact/${c._id}`,{status:e.target.value});load()}}>{['New','Contacted','In Progress','Converted','Closed'].map(x=><option key={x}>{x}</option>)}</select><button className="iconDelete" onClick={async()=>{if(confirm('Delete inquiry?')){await api.delete(`/contact/${c._id}`);load()}}}>Delete</button></div></div>)}{!contacts.length&&<div className="empty">No inquiries yet.</div>}</div>:<>
          <form className="adminForm" onSubmit={save}><div className="formHeader"><div><span className="eyebrow">{editing?'EDIT':'CREATE'} · {title.toUpperCase()}</span><h2>{editing?'Edit item':`New ${title.slice(0,-1)}`}</h2></div>{editing&&<span className="editBadge">Editing</span>}</div>
          {isProduct&&<><div className="adminFields">{[['name','Product name'],['slug','Slug'],['tagline','Tagline'],['category','Category'],['websiteUrl','Product URL'],['documentationUrl','Documentation URL']].map(([k,l])=><input key={k} placeholder={l} value={form[k]||''} onChange={e=>setField(k,e.target.value)}/>) }<select value={form.status} onChange={e=>setField('status',e.target.value)}>{['Live','Beta','Coming Soon','Archived'].map(x=><option key={x}>{x}</option>)}</select><textarea placeholder="Short description" value={form.description||''} onChange={e=>setField('description',e.target.value)}/><textarea placeholder="Long description" value={form.longDescription||''} onChange={e=>setField('longDescription',e.target.value)}/></div><h3>Features</h3>{form.features.map((f,i)=><div className="repeat" key={i}><input placeholder="Feature title" value={f.title||''} onChange={e=>{const a=[...form.features];a[i]={...a[i],title:e.target.value};setField('features',a)}}/><input placeholder="Feature description" value={f.description||''} onChange={e=>{const a=[...form.features];a[i]={...a[i],description:e.target.value};setField('features',a)}}/></div>)}<button type="button" className="btn secondary" onClick={()=>setField('features',[...form.features,{title:'',description:''}])}>+ Add feature</button></>}
          {isContent&&<div className="adminFields">{[['title','Title'],['slug','Slug'],['category','Category'],['industry','Industry'],['department','Department'],['location','Location'],['employmentType','Employment type'],['experienceLevel','Experience level'],['author','Author'],['coverImage','Cover image URL']].map(([k,l])=><input key={k} placeholder={l} value={form[k]||''} onChange={e=>setField(k,e.target.value)}/>) }<textarea placeholder="Description / excerpt" value={form.description||''} onChange={e=>setField('description',e.target.value)}/><textarea placeholder="Main content" value={form.content||''} onChange={e=>setField('content',e.target.value)}/><textarea placeholder="Challenge" value={form.challenge||''} onChange={e=>setField('challenge',e.target.value)}/><textarea placeholder="Solution" value={form.solution||''} onChange={e=>setField('solution',e.target.value)}/><input placeholder="Technologies (comma separated)" value={form.technologies||''} onChange={e=>setField('technologies',e.target.value)}/><input placeholder="Results (comma separated)" value={form.results||''} onChange={e=>setField('results',e.target.value)}/><textarea placeholder="Requirements (comma separated)" value={form.requirements||''} onChange={e=>setField('requirements',e.target.value)}/><textarea placeholder="Responsibilities (comma separated)" value={form.responsibilities||''} onChange={e=>setField('responsibilities',e.target.value)}/></div>}
          {isTestimonial&&<div className="adminFields"><textarea placeholder="Customer quote" value={form.quote||''} onChange={e=>setField('quote',e.target.value)}/><input placeholder="Customer name" value={form.customerName||''} onChange={e=>setField('customerName',e.target.value)}/><input placeholder="Position" value={form.position||''} onChange={e=>setField('position',e.target.value)}/><input placeholder="Company" value={form.company||''} onChange={e=>setField('company',e.target.value)}/><input placeholder="Photo URL" value={form.photo||''} onChange={e=>setField('photo',e.target.value)}/></div>}
          <div className="formFooter"><button className="btn primary" disabled={loading}>{loading?'Saving...':editing?'Save changes':`Create ${title.slice(0,-1)}`}</button>{editing&&<button type="button" className="btn secondary" onClick={reset}>Cancel</button>}</div></form>
          <div className="adminList"><div className="listHeader"><div><span className="eyebrow">LIBRARY</span><h2>{title}</h2></div></div>{filtered.map(x=><div className="adminRow" key={x._id}><div className="rowIdentity"><span className="rowIcon">{isProduct?'▦':isTestimonial?'♡':'◈'}</span><div><b>{x.name||x.title||x.customerName}</b><span>{x.category||x.industry||x.company||x.status||'Published'} · {x.slug||''}</span></div></div><div className="actions"><span className={`statusBadge ${String(x.status||'Live').toLowerCase().replace(' ','-')}`}>{x.status||'Published'}</span><button className="btn secondary small" onClick={()=>edit(x)}>Edit</button><button className="iconDelete" onClick={()=>remove(x._id)}>Delete</button></div></div>)}{!filtered.length&&<div className="empty">No {title.toLowerCase()} found.</div>}</div></>}
      </>}
    </div></main></div>;
}
