import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
import './SiteCustomizer.css';

const defaults = {
  businessType:'technology', name:'primeStack', tagline:'Software that moves your business forward.', description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.', email:'hello@primestack.dev', phone:'', logoUrl:'', faviconUrl:'', primaryColor:'#111827', accentColor:'#2563eb', backgroundColor:'#ffffff', textColor:'#111827',
  home:{eyebrow:'SOFTWARE PRODUCT COMPANY', title:'Software that moves your business forward.', description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.', primaryCtaLabel:'Explore products', secondaryCtaLabel:'Work with us', productsEyebrow:'OUR PRODUCTS', productsTitle:'Software built to matter.', ctaEyebrow:'BUILD WITH US', ctaTitle:'Have a software idea?', ctaText:"Let's turn your complex business challenge into a product people love to use."},
  pages:{services:{eyebrow:'CAPABILITIES',title:'Services',text:'From product strategy to scalable infrastructure, we build around the way your business actually works.'},about:{eyebrow:'THE COMPANY',title:'We build what comes next.',text:'primeStack turns complex business problems into elegant, dependable digital products.'},technology:{eyebrow:'ENGINEERING',title:'Technology expertise',text:'Modern tools selected for reliability, performance, security and maintainability.'},contact:{eyebrow:"LET'S TALK",title:'Build something valuable.',text:'Tell us what you are building, what problem you need to solve and where you want to go next.'},products:{eyebrow:'PRODUCT PORTFOLIO',title:'Products',text:'Purpose-built solutions designed to simplify work, unlock insight and accelerate growth.'},caseStudies:{eyebrow:'PROVEN OUTCOMES',title:'Case studies',text:'Real projects, real challenges, measurable results.'},blog:{eyebrow:'INSIGHTS',title:'Blog',text:'Ideas, lessons and practical insights from our team.'},careers:{eyebrow:'JOIN THE TEAM',title:'Careers',text:'Build meaningful products with a team that cares about quality.'}},
  services:[], technologies:[], values:[], stats:[{value:'10+',label:'Products'},{value:'50K+',label:'Users served'},{value:'99.9%',label:'Uptime'},{value:'8+',label:'Years experience'}],
  footer:{description:'We build dependable solutions that create measurable business value.',copyright:'All rights reserved.'}, seo:{title:'',description:''}
};

const clone = value => JSON.parse(JSON.stringify(value));

export default function SiteCustomizer(){
  const [form,setForm]=useState(defaults),[status,setStatus]=useState('loading'),[message,setMessage]=useState('');
  useEffect(()=>{api.get('/site-settings').then(r=>{setForm({...defaults,...r.data.data,home:{...defaults.home,...r.data.data.home},pages:{...defaults.pages,...r.data.data.pages},footer:{...defaults.footer,...r.data.data.footer}});setStatus('ready')}).catch(e=>{setMessage(e.response?.data?.message||'Unable to load website settings.');setStatus('error')})},[]);
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  const setHome=(key,value)=>setForm(f=>({...f,home:{...f.home,[key]:value}}));
  const setPage=(page,key,value)=>setForm(f=>({...f,pages:{...f.pages,[page]:{...f.pages[page],[key]:value}}}));
  const setFooter=(key,value)=>setForm(f=>({...f,footer:{...f.footer,[key]:value}}));
  const updateList=(key,index,value)=>setForm(f=>{const a=[...(f[key]||[])];a[index]=value;return {...f,[key]:a}});
  const addList=(key,value)=>setForm(f=>({...f,[key]:[...(f[key]||[]),value]}));
  const removeList=(key,index)=>setForm(f=>({...f,[key]:(f[key]||[]).filter((_,i)=>i!==index)}));
  const save=async e=>{e.preventDefault();setStatus('saving');setMessage('');try{await api.put('/site-settings',form);setStatus('ready');setMessage('Website settings published successfully.')}catch(e){setStatus('error');setMessage(e.response?.data?.message||'Unable to save website settings.')}};
  if(status==='loading')return <div className="siteCustomizerLoading">Loading website settings…</div>;
  return <form className="siteCustomizer" onSubmit={save}>
    <div className="siteCustomizerHead"><div><span>WEBSITE BUILDER</span><h1>Customize your website</h1><p>Change the business identity, page copy, services, technology list, colors and footer without editing code.</p></div><button className="siteSave" disabled={status==='saving'}>{status==='saving'?'Publishing…':'Publish changes'}</button></div>
    {message&&<div className={`siteMessage ${status==='error'?'error':'success'}`}>{message}</div>}
    <section className="siteCard"><div className="siteCardHead"><div><span>BUSINESS IDENTITY</span><h2>Company profile</h2></div></div><div className="siteGrid"><label>Business type<select value={form.businessType} onChange={e=>set('businessType',e.target.value)}><option value="technology">Technology / Software</option><option value="construction">Construction</option><option value="engineering">Engineering</option><option value="consulting">Consulting</option><option value="real-estate">Real Estate</option><option value="agency">Agency</option><option value="other">Other</option></select></label><label>Company name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Tagline<input value={form.tagline} onChange={e=>set('tagline',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Logo URL<input value={form.logoUrl} onChange={e=>set('logoUrl',e.target.value)}/></label><label>Favicon URL<input value={form.faviconUrl} onChange={e=>set('faviconUrl',e.target.value)}/></label><label className="wide">Company description<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label></div></section>
    <section className="siteCard"><div className="siteCardHead"><div><span>BRANDING</span><h2>Colors</h2></div></div><div className="siteColors"><label>Primary<input type="color" value={form.primaryColor} onChange={e=>set('primaryColor',e.target.value)}/><code>{form.primaryColor}</code></label><label>Accent<input type="color" value={form.accentColor} onChange={e=>set('accentColor',e.target.value)}/><code>{form.accentColor}</code></label><label>Background<input type="color" value={form.backgroundColor} onChange={e=>set('backgroundColor',e.target.value)}/><code>{form.backgroundColor}</code></label><label>Text<input type="color" value={form.textColor} onChange={e=>set('textColor',e.target.value)}/><code>{form.textColor}</code></label></div></section>
    <section className="siteCard"><div className="siteCardHead"><div><span>HOME PAGE</span><h2>Hero & calls to action</h2></div></div><div className="siteGrid"><label>Eyebrow<input value={form.home.eyebrow} onChange={e=>setHome('eyebrow',e.target.value)}/></label><label>Hero title<input value={form.home.title} onChange={e=>setHome('title',e.target.value)}/></label><label className="wide">Hero description<textarea value={form.home.description} onChange={e=>setHome('description',e.target.value)}/></label><label>Primary CTA<input value={form.home.primaryCtaLabel} onChange={e=>setHome('primaryCtaLabel',e.target.value)}/></label><label>Secondary CTA<input value={form.home.secondaryCtaLabel} onChange={e=>setHome('secondaryCtaLabel',e.target.value)}/></label><label>Products eyebrow<input value={form.home.productsEyebrow} onChange={e=>setHome('productsEyebrow',e.target.value)}/></label><label>Products title<input value={form.home.productsTitle} onChange={e=>setHome('productsTitle',e.target.value)}/></label><label>CTA eyebrow<input value={form.home.ctaEyebrow} onChange={e=>setHome('ctaEyebrow',e.target.value)}/></label><label>CTA title<input value={form.home.ctaTitle} onChange={e=>setHome('ctaTitle',e.target.value)}/></label><label className="wide">CTA text<textarea value={form.home.ctaText} onChange={e=>setHome('ctaText',e.target.value)}/></label></div></section>
    <section className="siteCard"><div className="siteCardHead"><div><span>ALL PAGES</span><h2>Page titles & introductions</h2></div></div>{Object.entries(form.pages).map(([page,data])=><div className="pageEditor" key={page}><h3>{page.replace(/([A-Z])/g,' $1')}</h3><div className="siteGrid"><label>Eyebrow<input value={data.eyebrow||''} onChange={e=>setPage(page,'eyebrow',e.target.value)}/></label><label>Title<input value={data.title||''} onChange={e=>setPage(page,'title',e.target.value)}/></label><label className="wide">Description<textarea value={data.text||''} onChange={e=>setPage(page,'text',e.target.value)}/></label></div></div>)}</section>
    <section className="siteCard"><div className="siteCardHead"><div><span>SERVICES</span><h2>Business capabilities</h2></div><button type="button" className="siteAdd" onClick={()=>addList('services',{name:'',description:''})}>+ Add service</button></div>{form.services.map((x,i)=><div className="repeatRow" key={i}><input placeholder="Service name" value={x.name||''} onChange={e=>updateList('services',i,{...x,name:e.target.value})}/><input placeholder="Short description" value={x.description||''} onChange={e=>updateList('services',i,{...x,description:e.target.value})}/><button type="button" onClick={()=>removeList('services',i)}>Remove</button></div>)}</section>
    <section className="siteCard"><div className="siteCardHead"><div><span>TECHNOLOGY & VALUES</span><h2>Lists shown on the site</h2></div><div><button type="button" className="siteAdd" onClick={()=>addList('technologies','')}>+ Technology</button> <button type="button" className="siteAdd" onClick={()=>addList('values','')}>+ Value</button></div></div><div className="twoLists"><div><h3>Technologies</h3>{form.technologies.map((x,i)=><div className="repeatRow" key={i}><input value={x} onChange={e=>updateList('technologies',i,e.target.value)}/><button type="button" onClick={()=>removeList('technologies',i)}>Remove</button></div>)}</div><div><h3>Values</h3>{form.values.map((x,i)=><div className="repeatRow" key={i}><input value={x} onChange={e=>updateList('values',i,e.target.value)}/><button type="button" onClick={()=>removeList('values',i)}>Remove</button></div>)}</div></div></section>
    <section className="siteCard"><div className="siteCardHead"><div><span>FOOTER</span><h2>Footer content</h2></div></div><div className="siteGrid"><label className="wide">Footer description<textarea value={form.footer.description||''} onChange={e=>setFooter('description',e.target.value)}/></label><label>Copyright text<input value={form.footer.copyright||''} onChange={e=>setFooter('copyright',e.target.value)}/></label></div></section>
    <div className="siteBottomSave"><button className="siteSave" disabled={status==='saving'}>{status==='saving'?'Publishing…':'Publish website changes'}</button></div>
  </form>;
}
