import { useEffect, useState } from 'react';
import { siteSettingsApi } from '../services/api.js';
import './SiteCustomizer.css';

const defaults = {
  businessType:'technology', name:'primeStack', tagline:'Software that moves your business forward.', description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.', email:'hello@primestack.dev', phone:'', logoUrl:'', faviconUrl:'', founderImageUrl:'', founderName:'Barack Isaac', founderCompanyName:'primeStack', primaryColor:'#111827', accentColor:'#2563eb', backgroundColor:'#ffffff', textColor:'#111827',
  nav:[{label:'Products',path:'/products',visible:true},{label:'Services',path:'/services',visible:true},{label:'Case Studies',path:'/case-studies',visible:true},{label:'Technology',path:'/technology',visible:true},{label:'Blog',path:'/blog',visible:true},{label:'Careers',path:'/careers',visible:true},{label:'About',path:'/about',visible:true}],
  sections:{hero:true,stats:true,products:true,services:true,caseStudies:true,testimonials:true,blog:true,cta:true,newsletter:true},
  home:{eyebrow:'SOFTWARE PRODUCT COMPANY',title:'Software that moves your business forward.',description:'We design, build and operate dependable software products that solve complex business problems and create measurable value.',founderName:'Barack Isaac',founderCompanyName:'primeStack',primaryCtaLabel:'Explore products',secondaryCtaLabel:'Work with us',productsEyebrow:'OUR PRODUCTS',productsTitle:'Software built to matter.',ctaEyebrow:'BUILD WITH US',ctaTitle:'Have a software idea?',ctaText:"Let's turn your complex business challenge into a product people love to use."},
  pages:{services:{eyebrow:'CAPABILITIES',title:'Services',text:'From product strategy to scalable infrastructure, we build around the way your business actually works.'},about:{eyebrow:'THE COMPANY',title:'We build what comes next.',text:'primeStack turns complex business problems into elegant, dependable digital products.'},technology:{eyebrow:'ENGINEERING',title:'Technology expertise',text:'Modern tools selected for reliability, performance, security and maintainability.'},contact:{eyebrow:"LET'S TALK",title:'Build something valuable.',text:'Tell us what you are building, what problem you need to solve and where you want to go next.'},products:{eyebrow:'PRODUCT PORTFOLIO',title:'Products',text:'Purpose-built solutions designed to simplify work, unlock insight and accelerate growth.'},caseStudies:{eyebrow:'PROVEN OUTCOMES',title:'Case studies',text:'Real projects, real challenges, measurable results.'},blog:{eyebrow:'INSIGHTS',title:'Blog',text:'Ideas, lessons and practical insights from our team.'},careers:{eyebrow:'JOIN THE TEAM',title:'Careers',text:'Build meaningful products with a team that cares about quality.'}},
  services:[], technologies:[], values:[], stats:[{value:'10+',label:'Products'},{value:'50K+',label:'Users served'},{value:'99.9%',label:'Uptime'},{value:'8+',label:'Years experience'}], footer:{description:'We build dependable solutions that create measurable business value.',copyright:'All rights reserved.'}, seo:{title:'',description:''}
};
const clone=v=>JSON.parse(JSON.stringify(v));
const fileToDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Unable to read the selected image.'));reader.readAsDataURL(file)});
const constructionPreset={businessType:'construction',name:'Your Construction Company',tagline:'Building quality. Delivering with confidence.',description:'We deliver reliable construction, civil works and engineering solutions from planning through completion.',home:{eyebrow:'CONSTRUCTION & ENGINEERING',title:'Building the places that move communities forward.',description:'From residential developments to commercial and civil infrastructure, we deliver quality projects safely, efficiently and on schedule.',founderName:'',founderCompanyName:'',primaryCtaLabel:'View projects',secondaryCtaLabel:'Request a quote',productsEyebrow:'OUR PROJECTS',productsTitle:'Projects built to last.',ctaEyebrow:'START A PROJECT',ctaTitle:'Have a project in mind?',ctaText:'Tell us about your construction project and our team will help you plan the next step.'},pages:{services:{eyebrow:'OUR CAPABILITIES',title:'Construction Services',text:'Professional construction and engineering services delivered with quality, safety and accountability.'},about:{eyebrow:'ABOUT THE COMPANY',title:'Building with purpose.',text:'We combine skilled teams, sound project management and dependable delivery to create lasting infrastructure.'},technology:{eyebrow:'ENGINEERING & METHODS',title:'Modern construction expertise',text:'We use proven construction methods, project controls and technology to improve quality and delivery.'},products:{eyebrow:'PROJECT PORTFOLIO',title:'Our Projects',text:'Explore selected residential, commercial and civil construction projects.'},caseStudies:{eyebrow:'PROJECT RESULTS',title:'Completed Projects',text:'Real construction projects, real challenges and measurable results.'},blog:{eyebrow:'CONSTRUCTION NEWS',title:'News & Insights',text:'Project updates, construction insights and company news.'},careers:{eyebrow:'JOIN OUR TEAM',title:'Careers',text:'Build a rewarding career delivering projects that make a difference.'}}};

export default function SiteCustomizer(){
 const [form,setForm]=useState(clone(defaults)),[status,setStatus]=useState('loading'),[message,setMessage]=useState('');
 useEffect(()=>{siteSettingsApi.get().then(r=>{const d=r.data?.data||{};const pages=Object.keys(defaults.pages).reduce((a,k)=>{a[k]={...defaults.pages[k],...(d.pages?.[k]||{})};return a},{});setForm({...clone(defaults),...d,nav:d.nav?.length?d.nav:clone(defaults.nav),sections:{...defaults.sections,...d.sections},home:{...defaults.home,...d.home},pages,footer:{...defaults.footer,...d.footer},seo:{...defaults.seo,...d.seo}});setStatus('ready')}).catch(e=>{setMessage(e.response?.data?.message||'Unable to load website settings.');setStatus('error')})},[]);
 const set=(key,value)=>setForm(f=>({...f,[key]:value}));
 const setHome=(key,value)=>setForm(f=>({...f,home:{...f.home,[key]:value}}));
 const setPage=(page,key,value)=>setForm(f=>({...f,pages:{...f.pages,[page]:{...f.pages[page],[key]:value}}}));
 const setFooter=(key,value)=>setForm(f=>({...f,footer:{...f.footer,[key]:value}}));
 const setSeo=(key,value)=>setForm(f=>({...f,seo:{...f.seo,[key]:value}}));
 const setSection=(key,value)=>setForm(f=>({...f,sections:{...f.sections,[key]:value}}));
 const updateList=(key,index,value)=>setForm(f=>{const a=[...(f[key]||[])];a[index]=value;return {...f,[key]:a}});
 const addList=(key,value)=>setForm(f=>({...f,[key]:[...(f[key]||[]),value]}));
 const removeList=(key,index)=>setForm(f=>({...f,[key]:(f[key]||[]).filter((_,i)=>i!==index)}));
 const moveNav=(i,dir)=>setForm(f=>{const a=[...f.nav],j=i+dir;if(j<0||j>=a.length)return f;[a[i],a[j]]=[a[j],a[i]];return {...f,nav:a}});
 const updateNav=(i,key,value)=>setForm(f=>{const a=[...f.nav];a[i]={...a[i],[key]:value};return {...f,nav:a}});
 const addNav=()=>setForm(f=>({...f,nav:[...f.nav,{label:'New page',path:'/',visible:true}]}));
 const removeNav=i=>setForm(f=>({...f,nav:f.nav.filter((_,x)=>x!==i)}));
 const applyConstruction=()=>setForm(f=>({...f,...clone(constructionPreset),nav:[{label:'Projects',path:'/products',visible:true},{label:'Services',path:'/services',visible:true},{label:'Completed Projects',path:'/case-studies',visible:true},{label:'News',path:'/blog',visible:true},{label:'Careers',path:'/careers',visible:true},{label:'About',path:'/about',visible:true},{label:'Contact',path:'/contact',visible:true}],services:[{name:'General Construction',description:'End-to-end building construction and project delivery.'},{name:'Civil Works',description:'Reliable infrastructure and civil engineering works.'},{name:'Commercial Projects',description:'Professional delivery of offices, retail and commercial developments.'}],technologies:['BIM & digital project management','Modern construction methods','Quality control systems'],values:['Safety first','Quality workmanship','On-time delivery','Integrity']}));
 const handleFounderPhoto=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return setMessage('Founder photo must be JPG, PNG or WebP.');if(file.size>8*1024*1024)return setMessage('Founder photo must be smaller than 8MB.');try{const dataUrl=await fileToDataUrl(file);const image=new Image();image.onload=async()=>{const max=1200,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image processing is unavailable.');ctx.drawImage(image,0,0,canvas.width,canvas.height);let quality=.78,compressed=canvas.toDataURL('image/jpeg',quality);while(compressed.length>650000&&quality>.45){quality-=.06;compressed=canvas.toDataURL('image/jpeg',quality)}set('founderImageUrl',compressed);setMessage('Founder photo prepared. Publish changes to make it live.')};image.onerror=()=>setMessage('The selected file is not a valid image.');image.src=dataUrl}catch(e){setMessage(e.message||'Unable to process the founder photo.')}};
 const save=async e=>{e.preventDefault();setStatus('saving');setMessage('');try{const founderName=String(form.home?.founderName||form.founderName||'').trim();const founderCompanyName=String(form.home?.founderCompanyName||form.founderCompanyName||form.name||'').trim();await siteSettingsApi.update({...form,founderName,founderCompanyName,home:{...form.home,founderName,founderCompanyName}});setStatus('ready');setMessage('Website settings published successfully.')}catch(e){setStatus('error');setMessage(e.response?.data?.message||'Unable to save website settings.')}};
 if(status==='loading')return <div className="siteCustomizerLoading">Loading website settings…</div>;
 return <form className="siteCustomizer" onSubmit={save}>
  <div className="siteCustomizerHead"><div><span>WEBSITE BUILDER</span><h1>Customize your website</h1><p>Configure your business identity, navigation, page content, homepage sections, services, branding and footer without editing code.</p></div><div className="siteHeadActions"><button type="button" className="sitePreset" onClick={applyConstruction}>Use construction preset</button><button className="siteSave" disabled={status==='saving'}>{status==='saving'?'Publishing…':'Publish changes'}</button></div></div>
  {message&&<div className={`siteMessage ${status==='error'?'error':'success'}`}>{message}</div>}
  <section className="siteCard"><div className="siteCardHead"><div><span>BUSINESS IDENTITY</span><h2>Company profile</h2></div></div><div className="siteGrid"><label>Business type<select value={form.businessType} onChange={e=>set('businessType',e.target.value)}><option value="technology">Technology / Software</option><option value="construction">Construction</option><option value="engineering">Engineering</option><option value="consulting">Consulting</option><option value="real-estate">Real Estate</option><option value="agency">Agency</option><option value="other">Other</option></select></label><label>Company name<input value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Tagline<input value={form.tagline} onChange={e=>set('tagline',e.target.value)}/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Logo URL<input value={form.logoUrl} onChange={e=>set('logoUrl',e.target.value)}/></label><label>Favicon URL<input value={form.faviconUrl} onChange={e=>set('faviconUrl',e.target.value)}/></label><label className="wide">Company description<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label></div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>HOMEPAGE MEDIA</span><h2>Founder profile</h2><p>Manage the founder name, company name and photo shown with the homepage founder presentation.</p></div></div><div className="siteGrid"><label>Founder name<input value={form.home.founderName||''} onChange={e=>setHome('founderName',e.target.value)} placeholder="Founder full name"/></label><label>Founder company name<input value={form.home.founderCompanyName||''} onChange={e=>setHome('founderCompanyName',e.target.value)} placeholder="Company or organization name"/></label></div><div className="founderPhotoEditor">{form.founderImageUrl?<img src={form.founderImageUrl} alt="Founder preview"/>:<div className="founderPhotoPlaceholder">No founder photo selected</div>}<div><input type="file" accept="image/jpeg,image/png,image/webp" onChange={handleFounderPhoto}/><button type="button" className="dangerText" onClick={()=>set('founderImageUrl','')}>Remove photo</button><small>JPG, PNG or WebP. Maximum source size 8MB; the image is resized to a smaller JPEG before publishing.</small></div></div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>NAVIGATION</span><h2>Menu builder</h2><p>Rename, reorder or hide public navigation links.</p></div><button type="button" className="siteAdd" onClick={addNav}>+ Add menu item</button></div>{form.nav.map((x,i)=><div className="navEditor" key={i}><input value={x.label||''} onChange={e=>updateNav(i,'label',e.target.value)} placeholder="Menu label"/><input value={x.path||''} onChange={e=>updateNav(i,'path',e.target.value)} placeholder="/path"/><label className="navVisible"><input type="checkbox" checked={x.visible!==false} onChange={e=>updateNav(i,'visible',e.target.checked)}/> Visible</label><button type="button" onClick={()=>moveNav(i,-1)}>↑</button><button type="button" onClick={()=>moveNav(i,1)}>↓</button><button type="button" className="dangerText" onClick={()=>removeNav(i)}>Remove</button></div>)}</section>
  <section className="siteCard"><div className="siteCardHead"><div><span>HOMEPAGE SECTIONS</span><h2>Section visibility</h2><p>Choose which homepage blocks are published.</p></div></div><div className="sectionToggles">{Object.entries({hero:'Hero',stats:'Statistics',products:'Products / Projects',services:'Services',caseStudies:'Case studies / Completed projects',testimonials:'Testimonials',blog:'Blog / News',cta:'Call to action',newsletter:'Newsletter'}).map(([k,l])=><label key={k} className="sectionToggle"><input type="checkbox" checked={form.sections[k]!==false} onChange={e=>setSection(k,e.target.checked)}/><span><b>{l}</b><small>{form.sections[k]!==false?'Visible on homepage':'Hidden from homepage'}</small></span></label>)}</div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>BRANDING</span><h2>Colors</h2></div></div><div className="siteColors">{[['primaryColor','Primary'],['accentColor','Accent'],['backgroundColor','Background'],['textColor','Text']].map(([k,l])=><label key={k}>{l}<input type="color" value={form[k]} onChange={e=>set(k,e.target.value)}/><code>{form[k]}</code></label>)}</div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>HOME PAGE</span><h2>Hero & calls to action</h2></div></div><div className="siteGrid"><label>Eyebrow<input value={form.home.eyebrow} onChange={e=>setHome('eyebrow',e.target.value)}/></label><label>Hero title<input value={form.home.title} onChange={e=>setHome('title',e.target.value)}/></label><label className="wide">Hero description<textarea value={form.home.description} onChange={e=>setHome('description',e.target.value)}/></label><label>Primary CTA<input value={form.home.primaryCtaLabel} onChange={e=>setHome('primaryCtaLabel',e.target.value)}/></label><label>Secondary CTA<input value={form.home.secondaryCtaLabel} onChange={e=>setHome('secondaryCtaLabel',e.target.value)}/></label><label>Products eyebrow<input value={form.home.productsEyebrow} onChange={e=>setHome('productsEyebrow',e.target.value)}/></label><label>Products title<input value={form.home.productsTitle} onChange={e=>setHome('productsTitle',e.target.value)}/></label><label>CTA eyebrow<input value={form.home.ctaEyebrow} onChange={e=>setHome('ctaEyebrow',e.target.value)}/></label><label>CTA title<input value={form.home.ctaTitle} onChange={e=>setHome('ctaTitle',e.target.value)}/></label><label className="wide">CTA text<textarea value={form.home.ctaText} onChange={e=>setHome('ctaText',e.target.value)}/></label></div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>ALL PAGES</span><h2>Page titles & introductions</h2></div></div>{Object.entries(form.pages).map(([page,data])=><div className="pageEditor" key={page}><h3>{page.replace(/([A-Z])/g,' $1')}</h3><div className="siteGrid"><label>Eyebrow<input value={data.eyebrow||''} onChange={e=>setPage(page,'eyebrow',e.target.value)}/></label><label>Title<input value={data.title||''} onChange={e=>setPage(page,'title',e.target.value)}/></label><label className="wide">Description<textarea value={data.text||''} onChange={e=>setPage(page,'text',e.target.value)}/></label></div></div>)}</section>
  <section className="siteCard"><div className="siteCardHead"><div><span>SERVICES</span><h2>Business capabilities</h2></div><button type="button" className="siteAdd" onClick={()=>addList('services',{name:'',description:''})}>+ Add service</button></div>{form.services.map((x,i)=><div className="repeatRow" key={i}><input placeholder="Service name" value={x.name||''} onChange={e=>updateList('services',i,{...x,name:e.target.value})}/><input placeholder="Short description" value={x.description||''} onChange={e=>updateList('services',i,{...x,description:e.target.value})}/><button type="button" onClick={()=>removeList('services',i)}>Remove</button></div>)}</section>
  <section className="siteCard"><div className="siteCardHead"><div><span>TECHNOLOGY & VALUES</span><h2>Lists shown on the site</h2></div><div><button type="button" className="siteAdd" onClick={()=>addList('technologies','')}>+ Technology</button> <button type="button" className="siteAdd" onClick={()=>addList('values','')}>+ Value</button></div></div><div className="twoLists"><div><h3>Technologies</h3>{form.technologies.map((x,i)=><div className="repeatRow" key={i}><input value={x} onChange={e=>updateList('technologies',i,e.target.value)}/><button type="button" onClick={()=>removeList('technologies',i)}>Remove</button></div>)}</div><div><h3>Values</h3>{form.values.map((x,i)=><div className="repeatRow" key={i}><input value={x} onChange={e=>updateList('values',i,e.target.value)}/><button type="button" onClick={()=>removeList('values',i)}>Remove</button></div>)}</div></div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>SEO</span><h2>Search metadata</h2><p>Optional metadata for search engines and browser previews.</p></div></div><div className="siteGrid"><label>SEO title<input value={form.seo.title||''} onChange={e=>setSeo('title',e.target.value)} placeholder="Defaults to company name"/></label><label className="wide">SEO description<textarea value={form.seo.description||''} onChange={e=>setSeo('description',e.target.value)} placeholder="Defaults to company description"/></label></div></section>
  <section className="siteCard"><div className="siteCardHead"><div><span>FOOTER</span><h2>Footer content</h2></div></div><div className="siteGrid"><label className="wide">Footer description<textarea value={form.footer.description||''} onChange={e=>setFooter('description',e.target.value)}/></label><label>Copyright text<input value={form.footer.copyright||''} onChange={e=>setFooter('copyright',e.target.value)}/></label></div></section>
  <div className="siteBottomSave"><button className="siteSave" disabled={status==='saving'}>{status==='saving'?'Publishing…':'Publish website changes'}</button></div>
 </form>;
}
