import 'dotenv/config';
import express from 'express';import cors from 'cors';import helmet from 'helmet';import cookieParser from 'cookie-parser';import rateLimit from 'express-rate-limit';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';
import inquiryConversationRoutes from './routes/inquiryConversation.routes.js';

const app=express();
const port=Number(process.env.PORT||5000);
const clientUrl=(process.env.CLIENT_URL||'http://localhost:5173').split(',').map(x=>x.trim()).filter(Boolean);
const JWT_SECRET=process.env.JWT_SECRET||(process.env.NODE_ENV==='production'?null:'development-only-secret-change-me');
if(!JWT_SECRET)throw new Error('JWT_SECRET must be configured in production');
app.set('trust proxy',1);app.use(helmet());app.use(cors({origin:(o,c)=>!o||clientUrl.includes(o)?c(null,true):c(new Error('CORS origin denied')),credentials:true}));app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true,limit:'3mb'}));app.use(cookieParser());
app.use(rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:true,legacyHeaders:false}));
const O={timestamps:true};
const Product=mongoose.model('Product',new mongoose.Schema({name:{type:String,required:true,trim:true},slug:{type:String,unique:true,index:true},tagline:String,description:String,longDescription:String,category:{type:String,default:'Business'},logo:String,screenshots:[String],features:[{title:String,description:String}],benefits:[String],useCases:[String],pricing:[{name:String,price:String,description:String,features:[String]}],faq:[{question:String,answer:String}],platforms:[String],technologies:[String],status:{type:String,enum:['Live','Beta','Coming Soon','Archived'],default:'Live'},websiteUrl:String,documentationUrl:String,releaseDate:Date,featured:{type:Boolean,default:false},published:{type:Boolean,default:true},seo:{title:String,description:String,keywords:[String],ogImage:String}},O));
const Content=mongoose.model('Content',new mongoose.Schema({type:{type:String,index:true},title:{type:String,required:true},slug:{type:String,index:true},description:String,content:String,category:String,industry:String,department:String,location:String,employmentType:String,experienceLevel:String,challenge:String,solution:String,technologies:[String],results:[String],metrics:[{label:String,value:String}],requirements:[String],responsibilities:[String],coverImage:String,author:String,published:{type:Boolean,default:true},publishedAt:Date,seo:Object},O));
const Contact=mongoose.models.Contact||mongoose.model('Contact',new mongoose.Schema({name:{type:String,required:true,trim:true},email:{type:String,required:true,lowercase:true,trim:true,index:true},company:String,phone:String,projectType:String,budget:String,message:{type:String,required:true},status:{type:String,enum:['New','Contacted','In Progress','Converted','Closed'],default:'New'}},O));
const Testimonial=mongoose.model('Testimonial',new mongoose.Schema({quote:{type:String,required:true},customerName:{type:String,required:true},position:String,company:String,photo:String,featured:{type:Boolean,default:false}},O));
const User=mongoose.model('User',new mongoose.Schema({name:{type:String,required:true,trim:true,minlength:2},email:{type:String,required:true,unique:true,lowercase:true,trim:true,index:true},password:{type:String,required:true,minlength:8,select:false},role:{type:String,enum:['Admin','Editor','Customer'],default:'Customer'},status:{type:String,enum:['Active','Suspended'],default:'Active'},lastLoginAt:Date},O));
const Newsletter=mongoose.model('Newsletter',new mongoose.Schema({email:{type:String,unique:true,lowercase:true,trim:true,index:true}},{timestamps:true}));

const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const ok=(res,data,message='OK',meta=null,status=200)=>res.status(status).json({success:true,message,data,...(meta?{meta}:{})});
const fail=(res,message,status=400)=>res.status(status).json({success:false,message});
const publicUser=u=>({id:u._id,name:u.name,email:u.email,role:u.role,status:u.status});
const tokenFor=u=>jwt.sign({id:u._id.toString(),role:u.role},JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'7d'});
const setSession=(res,u)=>res.cookie('ps_token',tokenFor(u),{httpOnly:true,sameSite:process.env.NODE_ENV==='production'?'none':'lax',secure:process.env.COOKIE_SECURE==='true'||process.env.NODE_ENV==='production',maxAge:7*24*60*60*1000,path:'/'});
const auth=(req,res,next)=>{try{const t=req.cookies.ps_token||String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return fail(res,'Authentication required',401);req.user=jwt.verify(t,JWT_SECRET);next()}catch{return fail(res,'Invalid or expired session',401)}};
const roles=(...allowed)=>(req,res,next)=>allowed.includes(req.user.role)?next():fail(res,'Insufficient permissions',403);

// Inquiry conversation endpoints use the same authenticated session as the CMS.
// auth MUST wrap this router; the router expects req.user to authorize admins/customers.
app.use('/api/inquiries', auth, inquiryConversationRoutes);

const emailValid=e=>/^\S+@\S+\.\S+$/.test(String(e||''));

app.get('/',(_q,r)=>ok(r,{name:'primeStack API',version:'2.0.0'}));
app.get('/health',(_q,r)=>ok(r,{status:'OK',database:mongoose.connection.readyState===1?'connected':'disconnected'}));

app.post('/api/auth/register',async(req,r)=>{try{const name=String(req.body?.name||'').trim(),email=String(req.body?.email||'').toLowerCase().trim(),password=String(req.body?.password||'');if(name.length<2)return fail(r,'Full name is required');if(!emailValid(email))return fail(r,'A valid email address is required');if(password.length<8)return fail(r,'Password must be at least 8 characters');if(await User.exists({email}))return fail(r,'An account with this email already exists',409);const u=await User.create({name,email,password:await bcrypt.hash(password,12),role:'Customer'});setSession(r,u);return ok(r,{user:publicUser(u)},'Account created',null,201)}catch(e){return fail(r,e.code===11000?'An account with this email already exists':e.message,500)}});
app.post('/api/auth/login',async(req,r)=>{try{const email=String(req.body?.email||'').toLowerCase().trim(),password=String(req.body?.password||''),u=await User.findOne({email}).select('+password');if(!u||u.status!=='Active'||!await bcrypt.compare(password,u.password))return fail(r,'Invalid email or password',401);u.lastLoginAt=new Date();await u.save();setSession(r,u);return ok(r,{user:publicUser(u)},'Signed in')}catch(e){return fail(r,e.message,500)}});
app.post('/api/auth/logout',(_q,r)=>{r.clearCookie('ps_token',{httpOnly:true,sameSite:process.env.NODE_ENV==='production'?'none':'lax',secure:process.env.COOKIE_SECURE==='true'||process.env.NODE_ENV==='production',path:'/'});return ok(r,null,'Signed out')});
app.get('/api/auth/me',auth,async(q,r)=>{const u=await User.findById(q.user.id);return u?ok(r,{user:publicUser(u)}):fail(r,'User not found',404)});
app.put('/api/auth/profile',auth,async(q,r)=>{try{const u=await User.findById(q.user.id);if(!u)return fail(r,'User not found',404);if(q.body.name!==undefined){const name=String(q.body.name).trim();if(name.length<2)return fail(r,'Name must contain at least 2 characters');u.name=name}if(q.body.password){if(String(q.body.password).length<8)return fail(r,'New password must be at least 8 characters');u.password=await bcrypt.hash(String(q.body.password),12)}await u.save();return ok(r,{user:publicUser(u)},'Profile updated')}catch(e){return fail(r,e.message,500)}});

app.get('/api/customer/dashboard',auth,roles('Customer'),async(q,r)=>{try{const u=await User.findById(q.user.id);if(!u)return fail(r,'User not found',404);const [products,requests]=await Promise.all([Product.find({published:true}).sort({featured:-1,createdAt:-1}).limit(6).lean(),Contact.find({email:u.email}).sort({createdAt:-1}).limit(8).lean()]);return ok(r,{user:publicUser(u),stats:{products:products.length,requests:await Contact.countDocuments({email:u.email})},products,requests})}catch(e){return fail(r,e.message,500)}});

app.get('/api/products',async(q,r)=>{try{const f={published:true};if(q.query.category)f.category=q.query.category;if(q.query.status)f.status=q.query.status;if(q.query.featured==='true')f.featured=true;if(q.query.search)f.$or=[{name:{$regex:q.query.search,$options:'i'}},{tagline:{$regex:q.query.search,$options:'i'}},{description:{$regex:q.query.search,$options:'i'}}];const limit=Math.min(Number(q.query.limit)||12,50),page=Math.max(Number(q.query.page)||1,1),[data,total]=await Promise.all([Product.find(f).sort({featured:-1,createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),Product.countDocuments(f)]);return ok(r,data,'Products',{page,limit,total,pages:Math.ceil(total/limit)})}catch(e){return fail(r,e.message,500)}});
app.get('/api/products/:slug',async(q,r)=>{const p=await Product.findOne({slug:q.params.slug,published:true}).lean();return p?ok(r,p):fail(r,'Product not found',404)});
app.post('/api/products',auth,roles('Admin','Editor'),async(q,r)=>{try{const p=await Product.create({...q.body,slug:slugify(q.body.slug||q.body.name)});return ok(r,p,'Product created',null,201)}catch(e){return fail(r,e.code===11000?'A product with this slug already exists':e.message)}});
app.put('/api/products/:id',auth,roles('Admin','Editor'),async(q,r)=>{try{const p=await Product.findByIdAndUpdate(q.params.id,q.body,{new:true,runValidators:true});return p?ok(r,p,'Product updated'):fail(r,'Product not found',404)}catch(e){return fail(r,e.message)}});
app.delete('/api/products/:id',auth,roles('Admin'),async(q,r)=>{const p=await Product.findByIdAndDelete(q.params.id);return p?ok(r,null,'Product deleted'):fail(r,'Product not found',404)});

for(const type of ['blog','case-studies','jobs']){app.get(`/api/${type}`,async(q,r)=>{try{const x=await Content.find({type,published:true}).sort({publishedAt:-1,createdAt:-1}).lean();return ok(r,x)}catch(e){return fail(r,e.message,500)}});app.get(`/api/${type}/:slug`,async(q,r)=>{const x=await Content.findOne({type,slug:q.params.slug,published:true}).lean();return x?ok(r,x):fail(r,'Content not found',404)});app.post(`/api/${type}`,auth,roles('Admin','Editor'),async(q,r)=>{try{return ok(r,await Content.create({...q.body,type,slug:slugify(q.body.slug||q.body.title),publishedAt:q.body.publishedAt||new Date()}),'Created',null,201)}catch(e){return fail(r,e.message)}});app.put(`/api/${type}/:id`,auth,roles('Admin','Editor'),async(q,r)=>{const x=await Content.findOneAndUpdate({_id:q.params.id,type},q.body,{new:true,runValidators:true});return x?ok(r,x,'Updated'):fail(r,'Content not found',404)});app.delete(`/api/${type}/:id`,auth,roles('Admin'),async(q,r)=>{const x=await Content.findOneAndDelete({_id:q.params.id,type});return x?ok(r,null,'Deleted'):fail(r,'Content not found',404)})}

app.post('/api/contact',async(q,r)=>{try{if(!q.body?.name||!emailValid(q.body?.email)||!q.body?.message)return fail(r,'Name, valid email and message are required');return ok(r,await Contact.create({...q.body,email:String(q.body.email).toLowerCase().trim()}),'Inquiry received',null,201)}catch(e){return fail(r,e.message)}});
app.get('/api/contact',auth,roles('Admin'),async(_q,r)=>ok(r,await Contact.find().sort({createdAt:-1}).lean()));
app.put('/api/contact/:id',auth,roles('Admin'),async(q,r)=>{const x=await Contact.findByIdAndUpdate(q.params.id,{status:q.body.status},{new:true,runValidators:true});return x?ok(r,x,'Updated'):fail(r,'Inquiry not found',404)});
app.delete('/api/contact/:id',auth,roles('Admin'),async(q,r)=>{const x=await Contact.findByIdAndDelete(q.params.id);return x?ok(r,null,'Deleted'):fail(r,'Inquiry not found',404)});

app.get('/api/testimonials',async(_q,r)=>ok(r,await Testimonial.find().sort({featured:-1,createdAt:-1}).lean()));
app.post('/api/testimonials',auth,roles('Admin','Editor'),async(q,r)=>ok(r,await Testimonial.create(q.body),'Created',null,201));
app.put('/api/testimonials/:id',auth,roles('Admin','Editor'),async(q,r)=>{const x=await Testimonial.findByIdAndUpdate(q.params.id,q.body,{new:true});return x?ok(r,x,'Updated'):fail(r,'Not found',404)});
app.delete('/api/testimonials/:id',auth,roles('Admin'),async(q,r)=>{const x=await Testimonial.findByIdAndDelete(q.params.id);return x?ok(r,null,'Deleted'):fail(r,'Not found',404)});
app.post('/api/newsletter',async(q,r)=>{try{const email=String(q.body?.email||'').toLowerCase().trim();if(!emailValid(email))return fail(r,'Valid email required');await Newsletter.updateOne({email},{$setOnInsert:{email}},{upsert:true});return ok(r,null,'Subscribed',null,201)}catch(e){return fail(r,e.message)}});

app.get('/api/dashboard/stats',auth,roles('Admin','Editor'),async(_q,r)=>{const[products,blog,caseStudies,jobs,newContacts,customers]=await Promise.all([Product.countDocuments(),Content.countDocuments({type:'blog'}),Content.countDocuments({type:'case-studies'}),Content.countDocuments({type:'jobs'}),Contact.countDocuments({status:'New'}),User.countDocuments({role:'Customer'})]);return ok(r,{products,blog,caseStudies,jobs,newContacts,customers})});
app.get('/api/admin/users',auth,roles('Admin'),async(q,r)=>{const page=Math.max(Number(q.query.page)||1,1),limit=Math.min(Number(q.query.limit)||25,100),filter=q.query.search?{$or:[{name:{$regex:q.query.search,$options:'i'}},{email:{$regex:q.query.search,$options:'i'}}]}:{};const[data,total]=await Promise.all([User.find(filter).select('-password').sort({createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),User.countDocuments(filter)]);return ok(r,data,'Users',{page,limit,total,pages:Math.ceil(total/limit)})});
app.put('/api/admin/users/:id/status',auth,roles('Admin'),async(q,r)=>{const status=['Active','Suspended'].includes(q.body.status)?q.body.status:null;if(!status)return fail(r,'Invalid status');const u=await User.findByIdAndUpdate(q.params.id,{status},{new:true}).select('-password');return u?ok(r,u,'User status updated'):fail(r,'User not found',404)});

const seed=async()=>{if(!mongoose.connection.readyState)return;const email=(process.env.ADMIN_EMAIL||'admin@primestack.dev').toLowerCase();if(!await User.exists({email})){const password=process.env.ADMIN_PASSWORD||'ChangeMe123!';if(process.env.NODE_ENV==='production'&&!process.env.ADMIN_PASSWORD)throw new Error('ADMIN_PASSWORD must be configured in production');await User.create({name:process.env.ADMIN_NAME||'PrimeStack Admin',email,password:await bcrypt.hash(password,12),role:'Admin'});}if(!await Product.countDocuments())await Product.insertMany([{name:'ProjectFlow',slug:'projectflow',tagline:'Project management without the overhead.',description:'A focused workspace for planning projects, coordinating teams and keeping delivery on track.',longDescription:'ProjectFlow brings planning, collaboration, reporting and accountability into one calm workspace.',category:'Productivity',platforms:['Web','Cloud'],technologies:['React','Node.js','MongoDB'],status:'Live',featured:true,features:[{title:'Real-time collaboration',description:'Keep teams aligned with shared workspaces and updates.'},{title:'Advanced reporting',description:'Turn delivery data into clear operational insight.'},{title:'Role-based permissions',description:'Give every team member the right level of access.'}],benefits:['Faster project delivery','Clearer ownership','Better operational visibility']},{name:'DataPulse',slug:'datapulse',tagline:'Business intelligence in real time.',description:'Dashboards and analytics that turn operational data into decisions.',category:'Analytics',platforms:['Web','API'],technologies:['React','Node.js','MongoDB'],status:'Beta',featured:true,features:[{title:'Live dashboards',description:'Monitor important metrics as they change.'},{title:'Flexible analytics',description:'Build views around the questions your business asks.'}]},{name:'SecureDesk',slug:'securedesk',tagline:'Customer support teams move faster.',description:'Ticketing, knowledge and customer communication in one secure platform.',category:'Security',platforms:['Web','Cloud'],technologies:['React','Node.js'],status:'Coming Soon',featured:true,features:[{title:'Smart ticketing',description:'Route and prioritize customer issues.'},{title:'Knowledge base',description:'Help customers find answers quickly.'}]},{name:'AutomateX',slug:'automatex',tagline:'Automate repetitive business workflows.',description:'Connect processes, approvals and notifications without unnecessary manual work.',category:'Automation',platforms:['Web','API'],technologies:['Node.js','MongoDB'],status:'Live',featured:true,features:[{title:'Workflow builder',description:'Model repeatable processes visually.'},{title:'API integrations',description:'Connect your existing systems.'}]}]);};

app.use((req,r)=>fail(r,'Route not found',404));
app.use((e,_q,r,_n)=>{console.error(e);fail(r,e.message||'Internal server error',e.status||500)});
(async()=>{try{if(process.env.MONGODB_URI)await mongoose.connect(process.env.MONGODB_URI);await seed();app.listen(port,()=>console.log(`primeStack API listening on ${port}`))}catch(e){console.error('Startup failed:',e);process.exit(1)}})();
export default app;
